name: XMRigMiner-iOS
options:
  bundleIdPrefix: com.iml1s
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    PRODUCT_NAME: XMRigMiner
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    INFOPLIST_FILE: XMRigMiner-iOS/Info.plist
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
    SWIFT_OBJC_BRIDGING_HEADER: "XMRigMiner-iOS/Sources/Bridge/XMRigMiner-iOS-Bridging-Header.h"
    CLANG_CXX_LANGUAGE_STANDARD: "c++17"
    CLANG_CXX_LIBRARY: "libc++"
    GCC_C_LANGUAGE_STANDARD: "c11"
    HEADER_SEARCH_PATHS:
      - "$(PROJECT_DIR)/XMRigCore/include"
      - "$(PROJECT_DIR)/XMRigCore/build/xmrig-6.25.0/src"
    LIBRARY_SEARCH_PATHS:
      - "$(PROJECT_DIR)/XMRigCore/output"

targets:
  XMRigMiner:
    type: application
    platform: iOS
    sources:
      - path: XMRigMiner-iOS/Sources
        excludes:
          - "**/.DS_Store"
      - path: XMRigCore/include
        type: group
        buildPhase: none
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.iml1s.xmrigminer
        TARGETED_DEVICE_FAMILY: "1,2"
        ONLY_ACTIVE_ARCH: NO
        ENABLE_BITCODE: NO
        ARCHS: arm64
        VALID_ARCHS: arm64
    info:
      path: XMRigMiner-iOS/Info.plist

schemes:
  XMRigMiner:
    build:
      targets:
        XMRigMiner: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
